### ISSUE TITLE
Question: Why does the `inputFile` got removed after a successful favicon generation?

### ISSUE THREAD

**Issue by tommykamkcm** [krehak/laravel-mix-favicon#5]
Hi @krehak, firstly I'd like to say thank you for building and maintaining this plugin. I always find it super useful!

I'm interested to know why does the plugin remove the source file under `resources/favicon/`? (see attached)

![image](https://user-images.githubusercontent.com/1722447/96555114-f3174300-12e9-11eb-93a0-fcd1f2431e80.png)

It'd be good if we can keep the it so that the local git repo will not get "confused". What do you think?

**Comment by krehak** [comment]
Hi, thank you very much. It is nice to see someone found it useful. I mainly build these plugins for myself and I'm used to clearing the source image file. I mean, for me there is no use for this image when you already parsed it to favicon. Also, when you run laravel-mix again, it will try to parse the image again, or even worse, when you have two or more images, it will probably parse all of them and it will mess it up. I didn't test it, but I guess it will break when there are multiple images.

You got the point to save the image for git repo. I just don't know (yet) what to do, when there are multiple images, or how to prevent parsing image every time you start the mix. I can look deeper into this problem in the evening. Thanks for posting.

**Comment by tommykamkcm** [comment]
Hi @krehak 

The way I see it is, we'll only need 1 source image e.g. a favicon.png in 260 x 260 px for an optimal result. (see attached `Submit an image...`)
![image](https://user-images.githubusercontent.com/1722447/96604880-2d9fd080-1328-11eb-88f5-b37085359b70.png)

What I'd recommend are:
1. Put only 1 favicon image into `resources/favicon`
2. Non-favicon images should go to the directory e.g. `resources/images` or `resources/img`
3. Keep the source image in `resources/favicon` after the favicon generation
4. Change the default value of `inputFile` to `favicon.{jpg,png,svg}`
![image](https://user-images.githubusercontent.com/1722447/96605169-75265c80-1328-11eb-8b70-15c9656029d5.png)

Hope it helps!

**Comment by krehak** [comment]
Well, I don't really want to force-set the specific file name. Developers should be able to use any image file. Anyway, I found a solution. Your problem is solved in commit f43a941e341a236ad93282b2609738db9928bb41. Please update your project to use the latest version (0.2.2).

Now you can use something like that:
```
mix.js(...)
    .favicon({
        // ...your previous config...
        cleaner: {
            use: true,
            path: 'parsed',
            timestamp: false
        }
    });
```

With these settings, you will be able to preserve original files. If you set `use` to false, it will not remove the file nor save the original. It will just leave the file as-is. But if you set `use` to true and set `path` to "parsed" (e.g.), now your file will be saved into the `resources/favicon/parsed/XYZ.png`. If you set `timestamp` to true, it will also add a timestamp to your saved file (so you can have a history if you want to).

Defaults are `use: true` and `path: null`, which means it will remove input file like before (it's noted in the documentation now), so already running projects won't be affected and will run like before. This solution will extend options as you requested and you still can use the old format.

**Comment by tommykamkcm** [comment]
Thanks @krehak, I'll try this out today 😄

**Comment by krehak** [comment]
I'm glad I helped :)
